### ISSUE TITLE
Indexerror under predict_all.py

### ISSUE THREAD

**Issue by WardDeb** [bio-ontology-research-group/deepgo#11]
Hi,

I'm trying to run predict_all.py on a fastafile with 306 sequences. If I try running with a reduced dataset (4 sequences) it seems to be running fine. With the full dataset, I get following error message:

```
Traceback (most recent call last):
  File "predict_all.py", line 131, in <module>
    main()
  File "/data/leuven/318/vsc31803/Programs/miniconda/envs/deepgo/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/data/leuven/318/vsc31803/Programs/miniconda/envs/deepgo/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/data/leuven/318/vsc31803/Programs/miniconda/envs/deepgo/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/data/leuven/318/vsc31803/Programs/miniconda/envs/deepgo/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "predict_all.py", line 18, in main
    results = predict_functions(sequences)
  File "predict_all.py", line 116, in predict_functions
    data = get_data(sequences)
  File "predict_all.py", line 67, in get_data
    data[i, j] = vocab[seq[j: (j + gram_len)]]
IndexError: index 1000 is out of bounds for axis 1 with size 1000
```
Would you have an idea what's wrong here? Could it have something to do with my protein sequence lengths? Is there certain cut-offs that I should be using? 

Thanks in advance,

Ward

**Comment by coolmaksat** [comment]
There is a limitation for sequence length, it works with maximum of 1002 aa sequences.

**Comment by WardDeb** [comment]
Thanks for the quick and concise answer!
