### ISSUE TITLE
Ask for help about load the model 

### ISSUE THREAD

**Issue by sjtuyf** [bio-ontology-research-group/deepgo#26]
Hi, 
    Thanks for your time to read my message. I am a student in Shanghai Jiao Tong university of China. 
    I am trying to run the script of predict_all.py, but got error. I tried to fix this , but failed at last. So I really need your help.
    The command I run is "predict_all.py -i test.fa ", and the error information is just like following.
     
Init
('Gram length:', 3)
('Vocabulary size:', 8000)
test start
data/models/model_cc.h5
Traceback (most recent call last):
  File "predict_all2.py", line 246, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "predict_all2.py", line 84, in main
    results = predict_functions(sequences, prot_ids, batch_size, threshold)
  File "predict_all2.py", line 227, in predict_functions
    init_models()
  File "predict_all2.py", line 216, in init_models
    model = load_model('data/models/model_%s.h5' % onto)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 373, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 987, in from_config
    config, custom_objects)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 2019, in reconstruct_from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/network.py", line 2001, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 375, in deserialize_keras_object
    return cls.from_config(cls_config)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 655, in from_config
    return cls(**config)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/input_layer.py", line 115, in __init__
    raise ValueError('Unrecognized keyword arguments:', kwargs.keys())
ValueError: ('Unrecognized keyword arguments:', dict_keys(['input_dtype']))
  
      The error showed the line166 of predict_all.py failed.  The line166 is "model = load_model('data/models/model_cc.h5')". So I could not load the model correctly. I also tried to load other models in the  folder of data/models/, unfortually all failed. In order to exclude to factor of load_model command, I try to load test.h5, which is made by ourself. It showed the load_model command is ok. So I am wondering whether the file of model_cc.h5 is uncomplete, as well as other H5 format model in the  folder of data/models/ ? or have other reasons?
     Could you help me to tackle this?
   
     Thank you very much in ahead for your help. I am looking forward to your reply. Thanks again.

Yours sincerely,
Yafei

**Comment by coolmaksat** [comment]
Dear Yafei,
This seems to be related to keras version. Did you install dependencies using requirements.txt?
The code was tested with python2 and I am not sure if it works with python3.

**Comment by sjtuyf** [comment]
> Dear Yafei,
> This seems to be related to keras version. Did you install dependencies using requirements.txt?
> The code was tested with python2 and I am not sure if it works with python3.

**Comment by sjtuyf** [comment]
Hi, 
    Thank you so much for your kind reply. I will try the script with python2.
    Thanks again for your help.


Best
Yafei
